name: Update VPN Subscription

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch: {}
  push:
    branches: [main]
    paths:
      - 'sources.txt'
      - 'sources_whitelist.txt'
      - 'manual.txt'
      - 'manual_whitelist.txt'
      - 'blacklist.txt'
      - 'scripts/**'
      - '.github/workflows/update.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install python deps
        run: pip install -r requirements.txt

      - name: Download Xray-core
        run: |
          curl -L -o xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip
          unzip -o xray.zip -d xray_bin
          chmod +x xray_bin/xray

      - name: Test configs & build subscriptions
        run: python -u scripts/build_subscription.py --xray-bin ./xray_bin/xray --workers 20 --max-output 15 --bypass-output 5 --max-latency-ms 400 --min-speed-kbps 350 --bypass-max-latency-ms 600 --bypass-min-speed-kbps 150 --round-gap 30 --skip-test


      - name: Commit updated subscriptionЫ
        run: |
          git config user.name "sub-bot"
          git config user.email "sub-bot@users.noreply.github.com"
          git add output/
          git diff --cached --quiet || git commit -m "auto-update subscription $(date -u +%F_%H-%M)"
          git push
